name = "JudiLing"
uuid = "b43a184b-0e9d-488b-813a-80fd5dbc9fd8"
version = "1.0.0"
authors = ["Xuefeng Luo", "Maria Heitmeier"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Embeddings = "c5bfea45-b7f1-5224-a596-15500f5db411"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
BSON = "0.3"
BenchmarkTools = "1.0 - 1.5"
CSV = "0.10"
Conda = "1.10.3"
DataFrames = "0.21, 1.6"
DataLoaders = "0.1.3"
DataStructures = "0.18"
Distances = "0.10"
Distributions = "0.23 - 0.25"
Embeddings = "=0.4.4, =0.4.6"
Flux = "0.0.0 - 0.16.7"
GZip = "0.6.2"
ProgressMeter = "1.9"
Requires = "1.3"
Statistics = "1.3 - 1.11.1"
julia = "1.9 - 1.12"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
